package finalproject;

public class Member extends Person {
   
	private static final long serialVersionUID = 1L;
	
	private String email;
    private String phone;
	private String membershipType;
	private boolean suspended;
    private int suspensionCount;

 // Constructor for UI (new member)
    public Member(String name, String email, String phone, String membershipType) {
        super(name); // id will be generated by DB
        this.email = email;
        this.phone = phone;
        this.membershipType = membershipType;
        this.suspended = false;
        this.suspensionCount = 0;
    }
    
 // Constructor for loading from DB
    public Member(int id, String name, String email, String phone, String membershipType,
                  boolean suspended, int suspensionCount) {
        super(name, id);
        this.email = email;
        this.phone = phone;
        this.membershipType = membershipType;
        this.suspended = suspended;
        this.suspensionCount = suspensionCount;
    }


 // Borrow limit
    public int getMaxBorrowLimit() {
        return membershipType.equalsIgnoreCase("Premium") ? 5 : 3;
    }

    // Suspension methods
    public boolean isSuspended() { return suspended; }

    //increments suspension count when a member gets suspended
    public void suspend() {
        this.suspended = true;
        this.suspensionCount++;
    }

    //lifts the suspension
    public void reinstate() {
        this.suspended = false;
    }

    public int getSuspensionCount() { return suspensionCount; }

    // Getters
    public String getEmail() { return email; }
    public String getPhone() { return phone; }
    public String getMembershipType() { return membershipType; }

    @Override
    public String toString() {
        return getName() + " (" + membershipType + ")" + (suspended ? " [Suspended]" : "");
    }
}