package finalproject;

public class Member extends Person {
<<<<<<< HEAD
   
	private static final long serialVersionUID = 1L;
	
	private String email;
    private String phone;
	private String membershipType;
	private boolean suspended;
    private int suspensionCount;

 // Constructor for UI (new member)
    public Member(String name, String email, String phone, String membershipType) {
        super(name); // id will be generated by DB
=======
    private String email;
    private String phone;
    private String membershipType;

    private boolean suspended;
    private int suspensionCount;

    // UI/new member (DB generates id)
    public Member(String name, String email, String phone, String membershipType) {
        super(name);
>>>>>>> 27eddc7 (Align Book model, DAO, service, and GUI; add LoanDAO and EmailService stub)
        this.email = email;
        this.phone = phone;
        this.membershipType = membershipType;
        this.suspended = false;
        this.suspensionCount = 0;
<<<<<<< HEAD
    }
    
 // Constructor for loading from DB
    public Member(int id, String name, String email, String phone, String membershipType,
                  boolean suspended, int suspensionCount) {
        super(name, id);
        this.email = email;
        this.phone = phone;
        this.membershipType = membershipType;
        this.suspended = suspended;
        this.suspensionCount = suspensionCount;
    }


 // Borrow limit
=======
    }

    // DB-loaded member
    public Member(int id, String name, String email, String phone, String membershipType,
                  boolean suspended, int suspensionCount) {
        super(id, name);
        this.email = email;
        this.phone = phone;
        this.membershipType = membershipType;
        this.suspended = suspended;
        this.suspensionCount = suspensionCount;
    }

>>>>>>> 27eddc7 (Align Book model, DAO, service, and GUI; add LoanDAO and EmailService stub)
    public int getMaxBorrowLimit() {
        return membershipType.equalsIgnoreCase("Premium") ? 5 : 3;
    }

<<<<<<< HEAD
    // Suspension methods
    public boolean isSuspended() { return suspended; }

    //increments suspension count when a member gets suspended
    public void suspend() {
        this.suspended = true;
        this.suspensionCount++;
    }

    //lifts the suspension
    public void reinstate() {
        this.suspended = false;
    }

    public int getSuspensionCount() { return suspensionCount; }

    // Getters
=======
    public boolean isSuspended() { return suspended; }
    public int getSuspensionCount() { return suspensionCount; }

    public void suspend() { this.suspended = true; this.suspensionCount++; }
    public void reinstate() { this.suspended = false; }

>>>>>>> 27eddc7 (Align Book model, DAO, service, and GUI; add LoanDAO and EmailService stub)
    public String getEmail() { return email; }
    public String getPhone() { return phone; }
    public String getMembershipType() { return membershipType; }

    @Override
    public String toString() {
<<<<<<< HEAD
        return getName() + " (" + membershipType + ")" + (suspended ? " [Suspended]" : "");
=======
        return name + " (" + membershipType + ")" + (suspended ? " [Suspended]" : "");
>>>>>>> 27eddc7 (Align Book model, DAO, service, and GUI; add LoanDAO and EmailService stub)
    }
}
