package finalproject;

public abstract class Person {
<<<<<<< HEAD
	protected String name;
    protected String id;

 // Constructor for new person (ID not yet assigned)
    protected Person(String name) {
        this.name = name;
    }

 // Constructor for loading from DB (ID assigned)
    protected Person(String name, int id) {
=======
    protected int id;      // DB primary key
    protected String name;

    // UI/new person (id generated by DB)
    protected Person(String name) {
>>>>>>> 27eddc7 (Align Book model, DAO, service, and GUI; add LoanDAO and EmailService stub)
        this.name = name;
    }

<<<<<<< HEAD
=======
    // DB-loaded person
    protected Person(int id, String name) {
        this.id = id;
        this.name = name;
    }

>>>>>>> 27eddc7 (Align Book model, DAO, service, and GUI; add LoanDAO and EmailService stub)
    public int getId() { return id; }
    public String getName() { return name; }

    public void setId(int id) { this.id = id; }
}
